[mypy]
check_untyped_defs = True
disallow_any_unimported = True
disallow_untyped_defs = True
ignore_missing_imports = False
show_error_codes = True
warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = True